[package]
name = "maximus-ui"
version = "0.1.0"
authors = ["Julien-cpsn <julien.caposiena@gmail.com>"]
edition = "2021"

[dependencies]

# Workspace
maximus-api = { workspace = true }
anyhow = { workspace = true }

dioxus = { workspace = true, features = ["router", "fullstack"] }
dioxus-primitives = { git = "https://github.com/DioxusLabs/components", version = "0.0.1", default-features = false }

reqwest = "0.13.2"

[features]
default = []
web = ["dioxus/web"]
server = ["dioxus/server", "maximus-api/server"]
